// ==========================
// preassignedCommands.js
// ==========================

// Map of useful preassigned commands and questions
const commands = {
  // ========================== QUESTIONS ==========================
  "help": "You can ask me about soil health, crop recommendations, irrigation, pest control, fertilizer usage, and harvesting tips.",
  "soil ph": "To check soil pH, use a pH meter or test kit. Most crops grow best in soil with a pH between 6.0 and 7.5.",
  "water requirement": "Water needs depend on crop type, soil, and weather. Keep the soil consistently moist for healthy growth.",
  "fertilizer advice": "Fertilizer depends on the soil test. Use the right NPK balance for your crop and avoid over-fertilizing.",
  "pest control": "Control pests using integrated methods: manual removal, natural predators, and safe pesticides when necessary.",
  "crop rotation": "Rotate crops each season to keep the soil fertile and reduce pests. Avoid planting the same crop repeatedly in the same field.",
  "harvest tips": "Harvest when crops are mature. Look for signs like color, texture, or moisture level, depending on the crop.",
  "best crops for summer": "Summer crops include maize, watermelon, cotton, and tomato. Choose based on local soil and climate.",
  "best crops for winter": "Winter crops include wheat, cabbage, carrot, and pea. Check soil fertility before planting.",
  "soil fertility test": "Use soil testing kits or labs to check nitrogen, phosphorus, potassium levels, and pH.",
  "irrigation methods": "Common irrigation methods: drip, sprinkler, furrow, and surface irrigation.",
  "organic farming": "Use compost, biofertilizers, and natural pest control. Avoid synthetic chemicals for organic produce.",
  "disease control": "Identify plant diseases early and use integrated disease management (IDM) techniques.",
  "fertilizer types": "Use NPK fertilizers as per soil test. Organic options include compost, manure, and biofertilizers.",
  "weed control": "Use mulching, manual removal, or selective herbicides depending on crop type.",
  "crop spacing": "Maintain recommended spacing to avoid competition and ensure optimal growth.",
  "seed selection": "Use certified seeds of high-yield and disease-resistant varieties.",
  "green manure": "Grow green manure crops like legumes to improve soil fertility naturally.",
  "composting": "Compost organic waste to create nutrient-rich fertilizer for your fields.",
  "soil moisture check": "Use a soil moisture meter or simple hand squeeze method to check soil dampness.",
  "mulching tips": "Apply mulch to retain soil moisture, regulate temperature, and reduce weed growth.",
  "fertilizer schedule": "Follow crop-specific fertilizer schedules for balanced nutrient application.",
  "pesticide safety": "Always follow label instructions, wear protective gear, and avoid overuse.",
  "crop yield improvement": "Improve yield by proper spacing, soil fertility, pest management, and irrigation.",
  "crop diseases": "Common diseases: blight, wilt, rust, leaf spot. Use resistant varieties and proper treatment.",
  "frost protection": "Use mulching, covers, or sprinklers to protect crops from frost damage.",
  "pruning tips": "Prune plants to remove dead parts and improve airflow and sunlight penetration.",
  "greenhouse farming": "Greenhouses help regulate climate, reduce pests, and improve yield.",
  "plant nutrients": "Essential nutrients: N, P, K, Mg, Ca, S, micronutrients. Deficiency affects growth.",
  "soil pH correction": "Use lime to raise pH or sulfur to lower pH based on soil test results.",
  "seed germination tips": "Use fresh seeds, soak if needed, and maintain proper moisture and temperature.",
  "crop rotation benefits": "Reduces pests, improves soil fertility, and increases yield stability.",
  "soil erosion prevention": "Use contour farming, cover crops, and mulching to prevent soil loss.",
  "fertigation": "Apply fertilizers through irrigation systems for efficient nutrient delivery.",
  "crop pests": "Identify common pests and use integrated pest management techniques.",
  "water conservation": "Use drip irrigation, rainwater harvesting, and mulch to save water.",
  "planting season": "Plant according to local season and climate to maximize crop success.",
  "harvesting time": "Harvest when fruits or grains are mature but not overripe for best quality.",
  "post-harvest storage": "Store crops in dry, ventilated areas to prevent spoilage and loss.",
  "weed identification": "Identify weeds early and remove them manually or chemically if needed.",
  "biofertilizers": "Use Rhizobium, Azotobacter, or phosphate-solubilizing bacteria to improve soil.",
  "cover crops": "Grow cover crops to reduce erosion, improve fertility, and suppress weeds.",
  "soil aeration": "Regularly till or aerate soil to improve water and nutrient absorption.",
  "compost tea": "Use compost tea as a liquid fertilizer to enhance soil microbial activity.",
  "crop monitoring": "Regularly monitor crop growth, pest activity, and soil conditions.",
  "planting depth": "Plant seeds at recommended depth for optimal germination and growth.",
  "organic pesticide": "Use neem oil, garlic extract, or Bt-based products for safe pest control.",
  "crop diversification": "Plant multiple crops to reduce risk and improve soil health.",
  "farming equipment": "Use appropriate equipment for planting, irrigation, and harvesting to save labor.",
  "soil sampling": "Collect soil samples from multiple locations for accurate testing.",
  "crop calendar": "Maintain a calendar of planting, fertilizing, irrigation, and harvesting activities.",

  // ========================== COMMANDS ==========================
  "/owner": "Abhinav Ranjan - Founder of Project AgroScan, started at age 13.",
  "/about": "AgroScan is an innovative agriculture assistance platform providing crop, soil, and farming guidance.",
  "/contact": "Reach us at support@agroscan.com or via our social media handles.",
  "/version": "AgroScan v1.0.0 - Backend and AI systems running smoothly.",
  "/team": "The AgroScan team consists of developers, agriculture experts, and AI engineers.",
  "/subscription": "You are using the Pro version with access to all AI features.",
  "/faq": "Visit our FAQ page for answers to common questions about soil, crops, and irrigation.",
  "/privacy": "Your data is safe. We follow strict privacy policies.",
  "/terms": "Read our terms of service on the official website.",
  "/updates": "Latest updates and feature releases are available on our website.",
  "/support": "Contact our support team for any issues or queries regarding AgroScan.",
  "/features": "Explore all AgroScan features: crop advice, soil analysis, pest management, and more.",
  "/news": "Get the latest agricultural news and tips from our blog section.",
  "/tutorials": "Step-by-step guides to use AgroScan tools effectively.",
  "/partners": "AgroScan collaborates with agriculture institutions and tech partners.",
  "/donate": "Support AgroScan by donating to our innovation initiatives.",
  "/feedback": "Share your feedback to help improve AgroScan services.",
  "/careers": "Join our team! Check current openings for developers and agriculture experts.",
  "/events": "Upcoming workshops, webinars, and events are listed on our events page.",
  "/demo": "Request a demo of AgroScan features tailored to your farm or field.",
  "/blog": "Visit our blog for insights on sustainable farming practices.",
  "/guide": "Download AgroScan user guides for detailed instructions.",
  "/success": "Read success stories of farmers using AgroScan effectively.",
  "/community": "Join the AgroScan community forum for knowledge sharing.",
  "/alerts": "Enable alerts to get crop and soil updates directly on your device.",
  "/reminder": "Set reminders for irrigation, fertilization, or harvesting tasks.",
  "/tutorial": "Watch video tutorials to understand AgroScan features quickly.",
  "/chat": "Use the AI chat system to get answers for specific crop or soil queries.",
  "/updates": "Check the update log for recent improvements and fixes.",
  "/newsletter": "Subscribe to the newsletter to receive farming tips and updates.",
  "/safety": "Learn safety guidelines for handling fertilizers and pesticides.",
  "/regulations": "Check local agricultural regulations before planting.",
  "/analytics": "View detailed analytics of your farm data.",
  "/weather": "Get weather forecasts and alerts for your farm area.",
  "/reports": "Generate crop and soil reports using AgroScan tools.",
  "/knowledge": "Access knowledge resources for modern farming practices.",
  "/tools": "Discover tools available to support your farming activities.",
  "/reminders": "Manage all task reminders in one place.",
  "/supportchat": "Chat with our support team for real-time assistance.",
  "/insights": "Get AI insights on improving yield and soil health.",
  "/map": "View farm mapping and crop location tracking features.",
  "/diagnosis": "AI diagnosis of crop issues using soil and environmental data.",
  "/alerts": "Enable notifications for pests, disease, and irrigation needs.",
  "/tips": "Daily farming tips and best practices delivered to your account.",
  "/knowledgebase": "Browse AgroScan knowledge base for guidance.",
  "/communityforum": "Engage with other farmers and experts in AgroScan forums.",
  "/resources": "Download templates, charts, and checklists for farming.",
  "/tutorialsplus": "Advanced tutorials for using AI recommendations effectively.",
  "/eventsplus": "Special events for training and learning opportunities.",
  "/feedbackplus": "Submit detailed feedback on AI responses and platform features."
};

// Function to get a command response if it exists
export function getPreassignedCommand(message) {
  const key = message.trim().toLowerCase();
  return commands[key] || null; // return null if no match
}
